global:
  useCombinedDb: true
  useCloudSql: false
  externalUrl: https://dev.magda.io
  image:
    pullPolicy: Always
  rollingUpdate:
    maxUnavailable: 1
  enablePriorityClass: true
  defaultContactEmail: "magda-test@googlegroups.com"
  enableMultiTenants: false

tags:
  all: true
  ingress: true
  connectors: true
  minion-broken-link: true
  minion-linked-data-rating: true
  minion-visualization: true
  minion-format: true

magda:
  openfaas:
    operator: 
      createCRD: false
  minion-broken-link:
    domainWaitTimeConfig:
      data.csiro.au: 5
      data.gov.au: 5
      data.act.gov.au: 30
  magda-core:
    ingress:
      hostname: dev.magda.io
      ingressClass: nginx
      enableTls: true
      domains:
        - dev.magda.io
        - "*.dev.magda.io"

    gateway:
      enableCkanRedirection: false
      enableAuthEndpoint: true
      enableHttpsRedirection: true
      auth:
        facebookClientId: "173073926555600"
        vanguardWsFedIdpUrl: https://thirdparty.authentication.business.gov.au/fas/v2/wsfed12/authenticate
        vanguardWsFedRealm: https://environment.magda.io/integration-test-2
      authPlugins:
      - key: google
        baseUrl: http://magda-auth-google
      - key: ckan
        baseUrl: http://magda-auth-ckan
      - key: internal
        baseUrl: http://magda-auth-internal
      - key: arcgis
        baseUrl: http://magda-auth-arcgis
      cors:
        credentials: true
        origin: true
      helmet:
        frameguard: false
      cookie:
        # Set sameSite to "none" to explicitly allow cross-site cookie
        # It's only for allowing frontend local dev site to login to remote dev instance
        # Should not be set to "none" for a production site
        sameSite: "none"
      csp:
        directives:
          scriptSrc:
            - "'self'"
            - browser-update.org
            - "'unsafe-inline'"
          objectSrc:
            - "'none'"
          reportUri: https://sdga.report-uri.com/r/d/csp/enforce

    combined-db:
      waleBackup:
        method: WAL
        gsPrefix: "gs://magda-postgres-backups-asia/dev"
        executionTime: 03:00
        googleApplicationCreds:
          secretName: storage-account-credentials
          fileName: TerriaJS-5e042b649f8a.json
      data:
        storage: 250Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: DoesNotExist

    elasticsearch:
      data:
        storage: 200Gi
        heapSize: 500m
        resources:
          requests:
            cpu: 200m
            memory: 1000Mi
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: cloud.google.com/gke-preemptible
                      operator: DoesNotExist
      backup:
        googleApplicationCreds:
          secretName: storage-account-credentials
          fileName: db-service-account-private-key.json

    indexer:
      readSnapshots: false
      makeSnapshots: false
      elasticsearch:
        useGcsSnapshots: true
        gcsSnapshotBucket: "magda-es-snapshots-dev"
        gcsSnapshotClient: "default"

    web-server:
      fallbackUrl: "https://data.gov.au"
      showNotificationBanner: false
      featureFlags:
        cataloguing: true
        publishToDga: true
        placeholderWorkflowsOn: false
        datasetApprovalWorkflowOn: true
        useStorageApi: true
      vocabularyApiEndpoints:
        - "https://vocabs.ands.org.au/repository/api/lda/abares/australian-land-use-and-management-classification/version-8/concept.json"
        - "https://vocabs.ands.org.au/repository/api/lda/neii/australian-landscape-water-balance/version-1/concept.json"
        - "https://vocabs.ands.org.au/repository/api/lda/ands-nc/controlled-vocabulary-for-resource-type-genres/version-1-1/concept.json"

    correspondence-api:
      alwaysSendToDefaultRecipient: true
      smtpHostname: "smtp.mailgun.org"
      smtpPort: 2525

# auth plugin for google
magda-auth-google:
  googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"

magda-auth-arcgis:
  arcgisClientId: "d0MgVUbbg5Z6vmWo"

# Connectors settings is built in local-deployment chart value file but you can override as the followings:
# e.g. dga connector:
# connector-dga:
#   config:
#     id: dga
#     name: "data.gov.au"
#     sourceUrl: "https://data.gov.au/data/"
#     pageSize: 1000
#     ignoreHarvestSources: ["*"]
