global:
  rollingUpdate:
    maxUnavailable: 1000
  image:
    imagePullSecret: "regcred"
    pullPolicy: Always
  exposeNodePorts: false
  enablePriorityClass: false
  defaultContactEmail: "magda-test@googlegroups.com"
  enableMultiTenants: false
  useCloudSql: true
  useCombinedDb: false
  urlProcessors:
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false
  connectors:
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false
  minions:
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false

tags:
  all: true
  cloud-sql-proxy: true
  ingress: true
  priorities: false
  connectors: false

magda:
  openfaas:
    operator: 
      createCRD: false
  magda-function-history-report:
    image:
      repository: docker.io/data61
      tag: 0.0.57-0
      pullPolicy: IfNotPresent
      imagePullSecret: false
  magda-core:
    ingress:
      ingressClass: nginx
      enableTls: true
      useDefaultCertificate: true
    cloud-sql-proxy:
      ## The cloud sql instance to connect to
      instanceConnectionName: terriajs:australia-southeast1:test-magda
    gateway:
      enableAuthEndpoint: true
      enableHttpsRedirection: true
      auth:
        facebookClientId: "173073926555600"
        vanguardWsFedIdpUrl: https://thirdparty.authentication.business.gov.au/fas/v2/wsfed12/authenticate
        vanguardWsFedRealm: https://environment.magda.io/integration-test-2
      authPlugins:
      - key: google
        baseUrl: http://magda-auth-google
      - key: ckan
        baseUrl: http://magda-auth-ckan
      - key: internal
        baseUrl: http://magda-auth-internal
      - key: arcgis
        baseUrl: http://magda-auth-arcgis
      autoscaler:
        enabled: false
      helmet:
        frameguard: false
      cors:
        credentials: true
        origin: true
      csp:
        directives:
          scriptSrc:
          - "'self'"
          - "'unsafe-inline'"
          - browser-update.org
          objectSrc:
          - "'none'"
          reportUri: https://sdga.report-uri.com/r/d/csp/enforce

    elasticsearch:
      data:
        heapSize: 500m
        pluginsInstall: "repository-gcs"
      backup:
        googleApplicationCreds:
          secretName: storage-account-credentials
          fileName: db-service-account-private-key.json
    indexer:
      resources:
        requests:
          cpu: 100m
          memory: 0
      readSnapshots: false
      makeSnapshots: false
      elasticsearch:
        useGcsSnapshots: true
        gcsSnapshotBucket: "magda-es-snapshots-dev"
        gcsSnapshotClient: "default"

    web-server:
      fallbackUrl: "https://data.gov.au"
      featureFlags:
        cataloguing: true
        publishToDga: true
        placeholderWorkflowsOn: false
        datasetApprovalWorkflowOn: true
        useStorageApi: true
      vocabularyApiEndpoints:
        - "https://vocabs.ands.org.au/repository/api/lda/abares/australian-land-use-and-management-classification/version-8/concept.json"
        - "https://vocabs.ands.org.au/repository/api/lda/neii/australian-landscape-water-balance/version-1/concept.json"
        - "https://vocabs.ands.org.au/repository/api/lda/ands-nc/controlled-vocabulary-for-resource-type-genres/version-1-1/concept.json"

    correspondence-api:
      alwaysSendToDefaultRecipient: true
      smtpHostname: "smtp.mailgun.org"
      smtpPort: 2525

    storage-api:
      minio:
        host: "localhost"
        port: 9000

    preview-map:
      image:
        repository: docker.io/data61
        tag: 0.0.57-0
        pullPolicy: IfNotPresent
        imagePullSecret: false

# auth plugin for google
magda-auth-google:
  googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
  image:
    tag: 1.0.0
    repository: docker.io/data61

magda-auth-ckan:
  ckanUrl: "https://data.gov.au/data"
  authPluginConfig:
    name: "Data.gov.au"
    loginFormExtraInfoHeading: "Register"
    loginFormExtraInfoContent: "To register a new [data.gov.au](https://data.gov.au/) account, [click here](https://data.gov.au/data/user/register)"
  image:
    tag: 1.0.0
    repository: docker.io/data61

magda-auth-internal:
  authPluginConfig:
    loginFormExtraInfoContent: "Forgot your password? Email [magda-test@googlegroups.com](magda-test@googlegroups.com)"
  image:
    tag: 1.0.0
    repository: docker.io/data61

magda-auth-arcgis:
  arcgisClientId: "d0MgVUbbg5Z6vmWo"
  image:
    tag: 1.0.0
    repository: docker.io/data61